In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/raw/aapl.csv", index_col="Date", parse_dates=True)
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-07-12 00:00:00-04:00,142.518502,142.625725,140.364293,140.851669,76299700,0.0,0.0
2021-07-13 00:00:00-04:00,140.393494,143.736900,140.003599,141.962845,100827100,0.0,0.0
2021-07-14 00:00:00-04:00,144.360769,145.793656,143.951360,145.384247,127050800,0.0,0.0
2021-07-15 00:00:00-04:00,145.471992,146.212798,143.376266,144.731171,106820300,0.0,0.0
2021-07-16 00:00:00-04:00,144.711667,145.978833,142.196806,142.693924,93251400,0.0,0.0

In [6]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-07-12 00:00:00-04:00,142.518502,142.625725,140.364293,140.851669,76299700,0.0,0.0
2021-07-13 00:00:00-04:00,140.393494,143.736900,140.003599,141.962845,100827100,0.0,0.0
2021-07-14 00:00:00-04:00,144.360769,145.793656,143.951360,145.384247,127050800,0.0,0.0
2021-07-15 00:00:00-04:00,145.471992,146.212798,143.376266,144.731171,106820300,0.0,0.0
2021-07-16 00:00:00-04:00,144.711667,145.978833,142.196806,142.693924,93251400,0.0,0.0

In [7]:
df['daily_return'] = (df['Close'] - df['Close'].shift(1)) / df['Close'].shift(1)
df[['Close', 'daily_return']].head()

                                Close  daily_return
Date
2021-07-12 00:00:00-04:00  140.851669           NaN
2021-07-13 00:00:00-04:00  141.962845      0.007889
2021-07-14 00:00:00-04:00  145.384247      0.024101
2021-07-15 00:00:00-04:00  144.731171     -0.004492
2021-07-16 00:00:00-04:00  142.693924     -0.014076

In [8]:
df['ma_20'] = df['Close'].rolling(window=20).mean()

In [9]:
df[['Close', 'ma_20']].head(25)

                                Close       ma_20
Date
2021-07-12 00:00:00-04:00  140.851669         NaN
2021-07-13 00:00:00-04:00  141.962845         NaN
2021-07-14 00:00:00-04:00  145.384247         NaN
2021-07-15 00:00:00-04:00  144.731171         NaN
2021-07-16 00:00:00-04:00  142.693924         NaN
2021-07-19 00:00:00-04:00  138.853394         NaN
2021-07-20 00:00:00-04:00  142.460007         NaN
2021-07-21 00:00:00-04:00  141.728912         NaN
2021-07-22 00:00:00-04:00  143.093582         NaN
2021-07-23 00:00:00-04:00  144.809128         NaN
2021-07-26 00:00:00-04:00  145.228287         NaN
2021-07-27 00:00:00-04:00  143.064316         NaN
2021-07-28 00:00:00-04:00  141.319534         NaN
2021-07-29 00:00:00-04:00  141.962845         NaN
2021-07-30 00:00:00-04:00  142.177338         NaN
2021-08-02 00:00:00-04:00  141.845932         NaN
2021-08-03 00:00:00-04:00  143.639420         NaN
2021-08-04 00:00:00-04:00  143.239761         NaN
2021-08-05 00:00:00-04:00  143.347000         NaN
2021-08-06 00:00:00-04:00  142.663696  142.752850
2021-08-09 00:00:00-04:00  142.614853  142.841010
2021-08-10 00:00:00-04:00  142.136536  142.849694
2021-08-11 00:00:00-04:00  142.390350  142.699999
2021-08-12 00:00:00-04:00  145.348251  142.730853
2021-08-13 00:00:00-04:00  145.553253  142.873820

In [10]:
df['volatility_20'] = df['daily_return'].rolling(window = 20).std()

In [12]:
df[['daily_return', 'volatility_20']].head(25)

                           daily_return  volatility_20
Date
2021-07-12 00:00:00-04:00           NaN            NaN
2021-07-13 00:00:00-04:00      0.007889            NaN
2021-07-14 00:00:00-04:00      0.024101            NaN
2021-07-15 00:00:00-04:00     -0.004492            NaN
2021-07-16 00:00:00-04:00     -0.014076            NaN
2021-07-19 00:00:00-04:00     -0.026914            NaN
2021-07-20 00:00:00-04:00      0.025974            NaN
2021-07-21 00:00:00-04:00     -0.005132            NaN
2021-07-22 00:00:00-04:00      0.009629            NaN
2021-07-23 00:00:00-04:00      0.011989            NaN
2021-07-26 00:00:00-04:00      0.002895            NaN
2021-07-27 00:00:00-04:00     -0.014900            NaN
2021-07-28 00:00:00-04:00     -0.012196            NaN
2021-07-29 00:00:00-04:00      0.004552            NaN
2021-07-30 00:00:00-04:00      0.001511            NaN
2021-08-02 00:00:00-04:00     -0.002331            NaN
2021-08-03 00:00:00-04:00      0.012644            NaN
2021-08-04 00:00:00-04:00     -0.002782            NaN
2021-08-05 00:00:00-04:00      0.000749            NaN
2021-08-06 00:00:00-04:00     -0.004767            NaN
2021-08-09 00:00:00-04:00     -0.000342       0.012798
2021-08-10 00:00:00-04:00     -0.003354       0.012712
2021-08-11 00:00:00-04:00      0.001786       0.011411
2021-08-12 00:00:00-04:00      0.020773       0.012361
2021-08-13 00:00:00-04:00      0.001410       0.011890

In [13]:
df['momentum_10'] = (df['Close'] - df['Close'].shift(10)) / df['Close'].shift(10)

In [14]:
df[['Close', 'momentum_10']].head(15)

                                Close  momentum_10
Date
2021-07-12 00:00:00-04:00  140.851669          NaN
2021-07-13 00:00:00-04:00  141.962845          NaN
2021-07-14 00:00:00-04:00  145.384247          NaN
2021-07-15 00:00:00-04:00  144.731171          NaN
2021-07-16 00:00:00-04:00  142.693924          NaN
2021-07-19 00:00:00-04:00  138.853394          NaN
2021-07-20 00:00:00-04:00  142.460007          NaN
2021-07-21 00:00:00-04:00  141.728912          NaN
2021-07-22 00:00:00-04:00  143.093582          NaN
2021-07-23 00:00:00-04:00  144.809128          NaN
2021-07-26 00:00:00-04:00  145.228287     0.031073
2021-07-27 00:00:00-04:00  143.064316     0.007759
2021-07-28 00:00:00-04:00  141.319534    -0.027958
2021-07-29 00:00:00-04:00  141.962845    -0.019127
2021-07-30 00:00:00-04:00  142.177338    -0.003620